version: '2'

services:
  homebridge:
    restart: always
    image: oznu/homebridge:1.7.8
    volumes:
    - ./config:/homebridge
    environment:
    - "PUID=${PUID}"
    - "PGID=${PGID}"
    - "TZ=${TZ}"
    networks:
      hostnet: {}

networks:
  hostnet:
    external: true
    name: host
