version: '2'

services:
  homebridge:
    restart: always
    image: oznu/homebridge:debian
    network_mode: "host"
    volumes:
    - ./config:/homebridge
    environment:
    - "PUID=${PUID}"
    - "PGID=${PGID}"
    - "TZ=${TZ}"
    - "PACKAGES=${PACKAGES}"